version: '3.5'
services:
  # If you want to specify where the data for a service is stored (i.e. specific drive, etc.) Change the
  # volume definition for the service. For example to put the influxdb data somewhere in the host change:
  #   volumes:
  #     - openag_influxdb:/var/lib/influxdb
  # to:
  #   volumes:
  #     - <path to existing directory on host>:/var/lib/influxdb

  # InfluxDB is a time series database that will hold our measurements etc.
  influxdb:
    image: influxdb:latest
    hostname: influx
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - openag_influxdb:/var/lib/influxdb

  # Chronograph is a UI for querying/exploring Influx
  chronograf:
    image: chronograf:latest
    hostname: chronograf
    container_name: chronograf
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - openag_chronograf:/var/lib/chronograf

  # Eclipse mosquitto is our MQTT broker for communicating with PFCs
  mqtt:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt
    restart: unless-stopped
    expose:
      - "1883"
      # - "9001"
    ports:
      - "1883:1883"
      # - "9001:9001"
    #volumes:
    #  - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  openag_mqtt_service:
    build: mqtt-service
    restart: unless-stopped
    depends_on:
      - mqtt

  openag_upload_file_service:
    build: upload-file-service
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - "80:80"
    tmpfs:
      - /tmp/downloads
    volumes:
    - openag_uploaded_images:/data/images


volumes:
  openag_influxdb:
  openag_chronograf:
  openag_uploaded_images:
  # openag_mqtt:
